---
abstract: 'The GRNOC Default Config parser'
author:
  - 'GRNOC Systems Engineering <syseng@grnoc.iu.edu>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.142690'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GRNOC-Config
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  XML::LibXML: '0'
  XML::Simple: '0'
  XML::XPath: '0'
version: v1.0.9
